module.exports = {
    CREATE_AUTHOR: 'CREATE_AUTHOR',
    INITIALIZE: 'INITIALIZE',
    UPDATE_AUTHOR: 'UPDATE_AUTHOR',
    DELETE_AUTHOR: 'DELETE_AUTHOR',
    CREATE_COURSE: 'CREATE_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    CREATE_FAN: 'CREATE_FAN',
    DELETE_FAN: 'DELETE_FAN',
};